### PR TITLE
Adding endpoint to switch entity

### PR DESCRIPTION
**Pull request by mareker**
Hi, I fix name, undefined value and "if"s from it. And unblock rename on zbbridge if endpoint is not defined.

### CODE REVIEW

**Review by mdaskalov — APPROVED** [review]

**Comment by mdaskalov** [comment]
I fixed some things using the online editor. now it should be okay to merge...

**Comment by mareker** [comment]
Perfect, thank you. Will you propagate it to npm?

**Comment by mdaskalov** [comment]
I’ve changed it a bit... 😀  The endpoint can be entered in the address field now because the separate endpoint field was too big. It is also (automatically) supported for other device types. 
Published 0.12.2 few minutes ago.

**Comment by mareker** [comment]
:) it's fine, maybe I will use it in my new house :) Currently I have only 2 zigbee devices and need endpoint just for full control one of them.

**Comment by mareker** [comment]
:) it's fine, maybe I will use it in my new house :) Currently I have only 2 zigbee devices and need endpoint just for full control one of them.

**Pull request merged**
